name: bookish_workspace
publish_to: none

environment:
  sdk: ^3.13.0
  flutter: '>=3.47.0'

workspace:
  - apps/store
  - apps/internal
  - packages/bookish_player
  - packages/bookish_cactus_transcription
