// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum CarPlayApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Generated class from Pigeon that represents data sent in messages.
struct CarBookItem: Hashable, CustomStringConvertible {
  var id: String
  var title: String
  var author: String
  var series: String
  var artworkPath: String? = nil
  var durationMs: Int64
  var positionMs: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CarBookItem? {
    let id = pigeonVar_list[0] as! String
    let title = pigeonVar_list[1] as! String
    let author = pigeonVar_list[2] as! String
    let series = pigeonVar_list[3] as! String
    let artworkPath: String? = nilOrValue(pigeonVar_list[4])
    let durationMs = pigeonVar_list[5] as! Int64
    let positionMs = pigeonVar_list[6] as! Int64

    return CarBookItem(
      id: id,
      title: title,
      author: author,
      series: series,
      artworkPath: artworkPath,
      durationMs: durationMs,
      positionMs: positionMs
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      title,
      author,
      series,
      artworkPath,
      durationMs,
      positionMs,
    ]
  }
  static func == (lhs: CarBookItem, rhs: CarBookItem) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return CarPlayApiPigeonInternal.deepEquals(lhs.id, rhs.id) && CarPlayApiPigeonInternal.deepEquals(lhs.title, rhs.title) && CarPlayApiPigeonInternal.deepEquals(lhs.author, rhs.author) && CarPlayApiPigeonInternal.deepEquals(lhs.series, rhs.series) && CarPlayApiPigeonInternal.deepEquals(lhs.artworkPath, rhs.artworkPath) && CarPlayApiPigeonInternal.deepEquals(lhs.durationMs, rhs.durationMs) && CarPlayApiPigeonInternal.deepEquals(lhs.positionMs, rhs.positionMs)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CarBookItem")
    CarPlayApiPigeonInternal.deepHash(value: id, hasher: &hasher)
    CarPlayApiPigeonInternal.deepHash(value: title, hasher: &hasher)
    CarPlayApiPigeonInternal.deepHash(value: author, hasher: &hasher)
    CarPlayApiPigeonInternal.deepHash(value: series, hasher: &hasher)
    CarPlayApiPigeonInternal.deepHash(value: artworkPath, hasher: &hasher)
    CarPlayApiPigeonInternal.deepHash(value: durationMs, hasher: &hasher)
    CarPlayApiPigeonInternal.deepHash(value: positionMs, hasher: &hasher)
  }

  public var description: String {
    return "CarBookItem(id: \(String(describing: id)), title: \(String(describing: title)), author: \(String(describing: author)), series: \(String(describing: series)), artworkPath: \(String(describing: artworkPath)), durationMs: \(String(describing: durationMs)), positionMs: \(String(describing: positionMs)))"
  }
}

private class CarPlayApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return CarBookItem.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class CarPlayApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? CarBookItem {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class CarPlayApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return CarPlayApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return CarPlayApiPigeonCodecWriter(data: data)
  }
}

class CarPlayApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = CarPlayApiPigeonCodec(readerWriter: CarPlayApiPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol CarPlayHostApi {
  func updateLibrary(books: [CarBookItem]) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class CarPlayHostApiSetup {
  static var codec: FlutterStandardMessageCodec { CarPlayApiPigeonCodec.shared }
  /// Sets up an instance of `CarPlayHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: CarPlayHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let updateLibraryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.bookish_player.CarPlayHostApi.updateLibrary\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateLibraryChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let booksArg = args[0] as! [CarBookItem]
        do {
          try api.updateLibrary(books: booksArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      updateLibraryChannel.setMessageHandler(nil)
    }
  }
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol CarPlayFlutterApiProtocol {
  func playBook(id idArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class CarPlayFlutterApi: CarPlayFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: CarPlayApiPigeonCodec {
    return CarPlayApiPigeonCodec.shared
  }
  func playBook(id idArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.bookish_player.CarPlayFlutterApi.playBook\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([idArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
