enum ImportHeading {
  openingFileBrowser,
  preparingSelection,
  copyingAudiobook,
  readingAudioInformation,
  analyzingChapters,
  extractingArtwork,
  savingToLibrary,
  removingOriginals,
  noTransferredAudiobooks,
  noFilesSelected,
  importCancelled,
  originalsRemain,
  fileAccessFailed,
  malformedMetadata,
  importFailed,
}
